export { default as AdminPage } from '@/pages/admin';
export { default as CreatorDetailPage } from '@/pages/creatorDetail';
export { default as HomePage } from '@/pages/home';
export { default as DailyBriefingPage } from '@/pages/dailyBriefing';
export { default as MyPage } from '@/pages/myPage';
export { default as NotFoundPage } from '@/pages/notFound';
export { default as CreatorListPage } from '@/pages/creatorList';
export { default as SearchResultPage } from '@/pages/searchResult';
export { default as SignupPage } from '@/pages/signup';
